#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);


#--------------------------------------------------
# actions for nethserver-roundcubemail-update event
#--------------------------------------------------

my $event = "nethserver-roundcubemail-next-update";

event_actions($event, 
             'initialize-default-databases' => '00',
             'nethserver-roundcubemail-conf' => '20'
);
templates2events("/etc/httpd/conf.d/roundcubemail.conf",  $event);
templates2events("/etc/httpd/conf.d/default-virtualhost.inc",  $event);
templates2events("./etc/roundcubemail/config.inc.php",  $event);
templates2events("/etc/opt/rh/rh-mariadb105/my.cnf.d/mariadb-server.cnf",  $event);
templates2events("/etc/opt/rh/rh-php73/php-fpm.d/000-roundcubemail.conf",  $event);
event_services($event, 'httpd' => 'reload');
event_services($event, 'rh-php73-php-fpm' => 'restart');
event_services($event, 'rh-mariadb105-mariadb@roundcubemail' => 'restart');


#--------------------------------------------------
# actions for trusted-networks-modify event
#--------------------------------------------------

$event = "trusted-networks-modify";

templates2events("/etc/httpd/conf.d/roundcubemail.conf", $event);
event_services($event, 'httpd' => 'reload');


#--------------------------------------------------
# actions for nethserver-sssd-save event
#--------------------------------------------------

$event = "nethserver-sssd-save";

templates2events("/etc/roundcubemail/config.inc.php",  $event);

# link to backup and restore event
event_actions("pre-backup-data", qw(
  nethserver-roundcubemail-rh-mariadb105-dump-database 60
));

event_actions("post-restore-data", qw(
  nethserver-roundcubemail-restore-rh-mariadb105-database 03
));
