#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

package esmith;

use strict;
use Errno;
use esmith::util;
use NethServer::Password;

exit(0) unless system('/usr/bin/mysql roundcubemail -e "describe users" &> /dev/null') != 0;


my $password = NethServer::Password::store('roundcubemail') || die('Could not generate roundcubemail password!');

my $commands = join("\n", 
	      "GRANT ALL PRIVILEGES ON `roundcubemail`.* TO 'roundcubemail'\@'localhost' IDENTIFIED BY '$password';",
	      "FLUSH PRIVILEGES;",
	      "CREATE DATABASE IF NOT EXISTS roundcubemail DEFAULT CHARACTER SET = 'utf8';"
     ) . "\n";

print $commands;

open(FH, '|-', '/usr/bin/mysql -B -f') || die("[ERROR] Could not connect to mysql");
print FH $commands;     
close(FH);

my @dirs = glob "/usr/share/doc/roundcubemail*";

system("/usr/bin/mysql roundcubemail < ".$dirs[0]."/SQL/mysql.initial.sql");


exit (0);
